/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-107541-g81ebf40efa-20220727"
#endif /* AVUTIL_FFVERSION_H */
